// Each #kernel tells which function to compile; you can have many kernels

#include "include/common.hlsl"

#pragma kernel CompositeSSR

// Create a RenderTexture with enableRandomWrite flag and set it
// with cs.SetTexture
RWTexture2D<float4> color_tex;
RWTexture2D<float4> ssr_tex;
[numthreads(FULL_SCREEN_CS_THREAD_X, FULL_SCREEN_CS_THREAD_Y, FULL_SCREEN_CS_THREAD_Z)] 
void CompositeSSR (uint3 id : SV_DispatchThreadID)
{
    color_tex[id.xy] = ssr_tex[id.xy];
}
